- name: Create address object
  paloaltonetworks.panos.panos_security_rule:
    provider: '{{ palo_provider }}'
    state: gathered
    gathered_filter: '*'
  register: security_rules


- name: list every address-object
  debug:
    msg: '{{ security_rules.gathered }}'

# - name: Create address object
#   paloaltonetworks.panos.panos_address_object:
#     provider: '{{ palo_provider }}'
#     name: '{{ object_name }}'
#     value: '{{ source_ip }}'
#     description: 'made by ansible'

# - name: Create object group 'block_from_outside'
#   paloaltonetworks.panos.panos_address_group:
#     provider: '{{ palo_provider }}'
#     name: 'Block_from_outside'
#     static_value: ['{{object_name}}']
#     state: merged

# - name: drop from outside
#   paloaltonetworks.panos.panos_security_rule:
#     provider: '{{ palo_provider }}'
#     rule_name: 'BLOCK_FROM_OUTSIDE'
#     description: 'Made by AWX'
#     source_zone: ['OUTSIDE']
#     source_ip: ['Block_from_outside']
#     destination_zone: ['any']
#     destination_ip: ['any']
#     application: ['any']
#     action: 'drop'
#     location: top
#     log_end: true