- name: Create internal object
  paloaltonetworks.panos.panos_address_object:
    provider: '{{ palo_provider }}'
    name: '{{ object_name }}'
    value: '{{ source_ip }}'
    description: 'made by ansible'

- name: Create object group 'Prod'
  paloaltonetworks.panos.panos_address_group:
    provider: '{{ provider }}'
    name: 'Block_from_outside'
    static_value: ['{{object_name}}']