---

- name: vars
  set_fact:
    commit: false
    gather: true
    palo_provider:
      ip_address: "{{ token_ip.stdout }}"
      api_key: "{{ token_key.stdout }}"

- name: gather every address-object
  paloaltonetworks.panos.panos_address_object:
    provider: '{{ palo_provider }}'
    gathered_filter: true
    state: gathered
  when: gather == true
  register: address_result

- name: gather every NAT policy
  paloaltonetworks.panos.panos_nat_rule2:
    provider: '{{ palo_provider }}'
    gathered_filter: true
    state: gathered
  when: gather == true
  register: nat_result

- name: list every address-object
  debug:
    msg: '{{ address_result.gathered }}'
  when: gather == true

- name: list every NAT policy
  debug:
    msg: '{{ nat_result.gathered }}'
  when: gather == true

- name: Create internal object
  paloaltonetworks.panos.panos_address_object:
    provider: '{{ palo_provider }}'
    name: '{{ object_name }}'
    value: '{{ source_ip }}'
    description: 'made by ansible'
  when: gather == false

- name: Create translated object
  paloaltonetworks.panos.panos_address_object:
    provider: '{{ palo_provider }}'
    name: '{{ object_name }}-NAT'
    value: '{{ NAT_ip }}'
    description: 'made by ansible'
  when: gather == false
  
- name: add a nat rule
  paloaltonetworks.panos.panos_nat_rule2:
    provider: '{{ palo_provider }}'
    name: '{{ object_name }} OUTSIDE'
    description: 'Made by Ansible'
    nat_type: 'ipv4'
    from_zones: ['{{ source_zone }}']
    to_zones: ['{{ dest_zone }}']
    to_interface: 'any'
    service: 'any'
    source_addresses: ['{{ object_name }}']
    destination_addresses: ['any']
    source_translation_type: 'static-ip'
    source_translation_static_translated_address: '{{ object_name }}-NAT'
    source_translation_static_bi_directional: true
  when: gather == false
  
- name: commit changes on PA
  paloaltonetworks.panos.panos_commit_firewall:
    provider: '{{ palo_provider }}'
    admins: ['AWX']
  when: commit == true and gather == false