- name: vars
  set_fact:
    create_vpn_user:  #bool
    disable_user:     #bool
    create_interface: #bool
    create_NAT:       #bool
    create_s2s_vpn:   #bool
    create_address_obj:
    create_address_group:
    create_ACL:

    block_ip_add_entry:
    block_ip_remove_entry:

    gather_users:     #bool
    gather_nat:       #bool
    gather_zones:     #bool
    gather_ACL:
    gather_address_group:

    commit_changes:   #bool

- name: Create VPN User
  include_role:
    name: PA_vpn_create_user
  when: create_vpn_user == true

- name: Disable VPN User
  include_role:
    name: PA_vpn_disable_user
  when: disable_user == true

- name: Create Interface
  include_role:
    name: PA_create_zones
  when: create_interface == true

- name: Create Sub-Interface
  include_role:
    name: PA_create_subint
  when: create_l3_subinterface == true

- name: Create NAT
  include_role:
    name: PA_create_nat
  when: create_NAT == true

- name: Create IKE Gateway
  include_role:
    name: PA_s2s_vpn
  when: create_s2s_vpn == true

- name: Create Address Object
  include_role:
    name: PA_create_address_obj
  when: create_address_obj == true

- name: Create Address Group
  include_role:
    name: PA_create_address_group
  when: create_address_group == true

- name: Create ACL
  include_role:
    name: PA_create_ACL
  when: create_ACL == true

- name: Commit Changes
  include_role:
    name: PA_commit
  when: commit_changes == true

- name: List Users
  include_role:
    name: PA_gather_users
  when: gather_users == true

- name: List NATs
  include_role:
    name: PA_gather_nat
  when: gather_nat == true

- name: List Zones
  include_role:
    name: PA_gather_zones
  when: gather_zones == true

- name: List ACL
  include_role:
    name: PA_gather_ACLs
  when: gather_ACL == true

- name: List Address Groups
  include_role:
    name: PA_gather_add_group
  when: gather_address_group == true