- name: vars
  set_fact:
    create_interface: # bool
    disable_user: # bool
    username: #str
    new_username: #str
    password_hash: # str
    palo_provider:
      ip_address: "{{ token_ip.stdout }}"
      api_key: "{{ token_key.stdout }}"

- name: Create VPN User
  include_role:
    name: PA_create_vpn_user
  when: create_vpn_user == true

- name: Disable VPN User
  include_role:
    name: PA_delete_vpn_user
  when: disable_user == true

- name: Create Interface
  include_role:
    name: PA_Zones
  when: create_interface == true