- name: vars
  set_fact:
    create_vpn_user:  #bool
    disable_user:     #bool
    delete_user:
    create_interface: #bool
    create_NAT:       #bool
    create_s2s_vpn:   #bool
    create_address_obj:
    create_address_group:
    create_ACL:
    create_outbound_NAT:
    create_zone:
    create_l3_subinterface:

    auto_to_main:

    block_ip:
    block_ip_remove:

    upgrade:

    gather_users:     #bool
    gather_nat:       #bool
    gather_zones:     #bool
    gather_ACL:
    gather_address_group:
    gather_blocked_ips:
    gather_address_obj:
    gather_IKE:

    commit_changes:   #bool

- name: Create VPN User
  include_role:
    name: PA_vpn_create_user
  when: create_vpn_user == true

- name: Disable VPN User
  include_role:
    name: PA_vpn_disable_user
  when: disable_user == true

- name: Delete VPN User
  include_role:
    name: PA_vpn_delete_user
  when: delete_user == true

- name: Create Interface
  include_role:
    name: PA_create_zones
  when: create_interface == true

- name: Create Sub-Interface
  include_role:
    name: PA_create_subint
  when: create_l3_subinterface == true

- name: Create NAT
  include_role:
    name: PA_create_nat
  when: create_NAT == true

- name: Change VPN Mode
  include_role:
    name: PA_auto_to_main
  when: auto_to_main == true

- name: Create Outbound NAT
  include_role:
    name: PA_create_outbound_nat
  when: create_outbound_NAT == true

- name: Create S2S VPN
  include_role:
    name: PA_create_zones
  when: create_zone == true

- name: Create Address Object
  include_role:
    name: PA_create_address_obj
  when: create_address_obj == true

- name: Create Address Group
  include_role:
    name: PA_create_address_group
  when: create_address_group == true

- name: Create ACL
  include_role:
    name: PA_create_ACL
  when: create_ACL == true

- name: Upgrade PA
  include_role:
    name: PA_upgrade
  when: upgrade == true

- name: Block an IP
  include_role:
    name: PA_block_ip
  when: block_ip == true

- name: Remove IP from Blocklist
  include_role:
    name: PA_block_ip_remove
  when: block_ip_remove == true

- name: Commit Changes
  include_role:
    name: PA_commit
  when: commit_changes == true

- name: List Users
  include_role:
    name: PA_gather_users
  when: gather_users == true

- name: List NATs
  include_role:
    name: PA_gather_nat
  when: gather_nat == true

- name: List Zones
  include_role:
    name: PA_gather_zones
  when: gather_zones == true

- name: List ACL
  include_role:
    name: PA_gather_ACLs
  when: gather_ACL == true

- name: List Address Objects
  include_role:
    name: PA_gather_address_obj
  when: gather_address_obj == true

- name: List Address Groups
  include_role:
    name: PA_gather_add_group
  when: gather_address_group == true

- name: List Blocked IPs
  include_role:
    name: PA_block_ip_get
  when: gather_blocked_ips == true

- name: List IKE Facts
  include_role:
    name: PA_gather_ike
  when: gather_IKE == true