- name: vars
  set_fact:
    palo_provider:
      ip_address: "{{ token_ip.stdout }}"
      api_key: "{{ token_key.stdout }}"


- name: gather zones
  paloaltonetworks.panos.panos_interface:
    provider: '{{ palo_provider }}'
    gathered_filter: true
    state: 'gathered'
  register: zone_gathered

- name: display zones
  debug:
    msg: '{{ zone_gathered.gathered }}'