- name: vars
  set_fact:
    palo_provider:
      ip_address: "{{ token_ip.stdout }}"
      api_key: "{{ token_key.stdout }}"

- name: gather zones
  paloaltonetworks.panos.panos_zone:
    provider: '{{ palo_provider }}'
    gathered_filter: true
    state: 'gathered'
  register: zone_gathered

# - name: create zone
#   paloaltonetworks.panos.panos_zone:
#     provider: '{{ palo_provider }}'
#     zone: 'dmz'
#     mode: 'layer3'

- name: add interface to zone
  paloaltonetworks.panos.panos_interface:
    provider: '{{ palo_provider }}'
    if_name: 'ethernet1/3'
    zone_name: 'dmz'
    enable_dhcp: false

- name: Create sub L3 interface
  paloaltonetworks.panos.panos_l3_subinterface:
    provider: '{{ palo_provider }}'
    name: "ethernet1/3.301"
    tag: 301
    enable_dhcp: false
    ip: '1.1.1.0/24'
    zone_name: "dmz"


# - name: display zones
#   debug:
#     msg: '{{ zone_gathered.gathered }}'