- name: vars
  set_fact:
    password: # str
    palo_provider:
      ip_address: "{{ token_ip.stdout }}"
      api_key: "{{ token_key.stdout }}"


- name: delete the DMZ zone
  paloaltonetworks.panos.panos_interface:
    provider: '{{ provider }}'
    gathered_filter: true
    state: 'gathered'
  register: zone_gathered

- name: display zones
  debug:
    msg: '{{ zone_gathered.gathered }}'