---

## TODO make a shit ton of files for every task in proper JSON and combine them into 1 json file to be converted to HTML

## ANCHOR hostname & IP
- name: grab hostname and IP's
  shell: hostname; ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p';
  register: ip

# ## ANCHOR device uptime
- name: get uptime
  shell: w | awk 'NR==1{print $2,$3}' | sed 's/,//g'
  register: uptime_days
# - name: Set Uptime Fact
#   set_fact:
#     uptime_days: "{{ (ansible_facts['uptime_seconds'] | int / 86400) | round(0) }}"

## ANCHOR last yum update
- name: Date of Last Update
  shell: "rpm -qa -last | awk '{print $2 , $4 , $5}' | sort -k3,3nr -k2,2M -k1,1 | uniq | head"
  when: ansible_facts['pkg_mgr'] == "yum"
  register: update

## ANCHOR last apt update
- name: Last Time apt/history.log was Modified
  shell: stat /var/log/apt/history.log | awk 'NR==6{print $1, $2}' | sed 's/Modify://g'
  register: apt_history
  when: ansible_facts['pkg_mgr'] == "apt"

## ANCHOR yum updateinfo (security/bug fixes)
- name: Check Fixes
  shell: 'yum updateinfo | grep "Update*" -A30'
  when: ansible_facts['pkg_mgr'] == "yum"
  register: Sec_Impact

## ANCHOR update the apt cache, stage upgrade
- name: Update apt Cache
  apt: 
    update_cache: yes
  when: ansible_facts['pkg_mgr'] == "apt"
  register: cache_results

## ANCHOR everything below is printing data

- name: Print Hostname & IP(s)
  debug:
    var: ip | to_nice_json
  register: jsonoutput

# - name: Print Hostname & IP(s)
#   debug:
#     msg:
#     - "Command - {{ ip.cmd }}"
#     - "Results - {{ ip.stdout_lines }}"
#   register: jsonoutput

- name: write json locally
  copy:
    content: "{{ jsonoutput | to_nice_json }}"
    dest: "/tmp/master.json"
  delegate_to: localhost

- name: Check for RedHat Based OS
  debug:
    msg: "Found RedHat-based Installation"
  #when: ansible_facts['pkg_mgr'] == "yum"
  register: redhat_found
  delegate_to: localhost
  

- name: add redhat to master.json
  lineinfile:
    path: /tmp/master.json
    line: "{{ redhat_found | to_nice_json }}"
    create: yes
  #when: ansible_facts['pkg_mgr'] == "yum"
  delegate_to: localhost
  
- name: Check for Debian Based OS
  debug:
    msg: "Found Debian-based Installation"
  #when: ansible_facts['pkg_mgr'] == "apt"
  register: debian_found
  delegate_to: localhost

- name: add debian to master.json
  lineinfile:
    path: /tmp/master.json
    line: "{{ debian_found | to_nice_json }}"
    create: yes
  #when: ansible_facts['pkg_mgr'] == "apt"
  delegate_to: localhost

- name: grab date of last yum usage
  lineinfile:
    path: /tmp/master.json
    line: "{{ update | to_nice_json }}"
    create: yes
  #when: ansible_facts['pkg_mgr'] == "yum"
  delegate_to: localhost

- name: grab date of last apt usage
  lineinfile:
    path: /tmp/master.json
    line: "{{ apt_history | to_nice_json }}"
    create: yes
  #when: ansible_facts['pkg_mgr'] == "apt"
  delegate_to: localhost

- name: grab uptime
  lineinfile:
    path: /tmp/master.json
    line: "{{ uptime_days | to_nice_json }}"
    create: yes
  delegate_to: localhost

- name: grab json file locally
  shell: cat /tmp/master.json
  register: hello
  delegate_to: localhost

- name: print the file
  debug:
    var: hello | unique
  


# - name: Print apt Success Check
#   debug:
#     msg: "The apt cache has successfully updated (equivalent of apt-get update)."
#   when: ansible_facts['pkg_mgr'] == "apt" and cache_results["cache_updated"] == true

# - name: Print apt Failure Check
#   debug:
#     msg: "The apt cache has failed it's update. Please manually troubleshoot"
#   when: ansible_facts['pkg_mgr'] == "apt" and cache_results["cache_updated"] == false

# - name: Print Bug/Security Fixes for yum
#   debug:
#     var: Sec_Impact | type_debug
#   when: ansible_facts['pkg_mgr'] == "yum"