- name: vars
  set_fact:
    password: # str
    palo_provider:
      ip_address: "{{ token_ip.stdout }}"
      api_key: "{{ token_key.stdout }}"

# - name: Show the address object.
#   paloaltonetworks.panos.panos_type_cmd:
#     provider: '{{ palo_provider }}'
#     cmd: 'get'
#     xpath: |
#       /config/shared/local-user-database
#   register: hi

- name: request password hash
  paloaltonetworks.panos.panos_op:
    provider: '{{ palo_provider }}'
    cmd: 'request password-hash password {{password}}'
  register: user_pw

- name: parsing
  copy:
    content: "{{ user_pw.stdout_lines[0].split()[5] | regex_replace('[,\"}]', '') }}"
    dest: "/tmp/fwdata.json"
  delegate_to: 172.16.101.182

- name: cat hash
  shell: cat /tmp/fwdata.json
  register: phash
  delegate_to: 172.16.101.182

- name: Show phash value
  debug:
    msg: "{{ user_pw.stdout_lines[0].split()[5] | regex_replace('[,\"}]', '') }}"

- name: Show phash value
  debug:
    msg: "{{ phash }}"

- name: Show the address object.
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ palo_provider }}'
    cmd: 'set'
    xpath: |
      /config/shared/local-user-database/user/entry[@name='testuser']
    element: <phash> {{phash}} </phash>




# - name: show user db
#   debug:
#     msg: '{{ hi.stdout }}'