- name: vars
  set_fact:
    palo_provider:
      ip_address: "{{ token_ip.stdout }}"
      api_key: "{{ token_key.stdout }}"

- name: Show the address object.
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ palo_provider }}'
    cmd: 'set'
    xpath: |
      /config/devices/entry[@name='localhost.localdomain']
      /vsys/entry[@name='vsys1']/local-user-database
      /user-group/entry[@name='RAVPN-USERS']/user
    element: "<member>testuser</member>"
#   register: hi


# - name: Create an address object using set.
#   paloaltonetworks.panos.panos_type_cmd:
#     provider: '{{ palo_provider }}'
#     xpath: |
#       /config/devices/entry[@name='localhost.localdomain']
#       /vsys/entry[@name='vsys1']
#       /address
#     element: |
#       <entry name="sales-block">
#         <ip-netmask>192.168.55.0/24</ip-netmask>
#         <description>Address CIDR for sales org</description>
#       </entry>


# - name: show user db
#   debug:
#     msg: '{{ hi.stdout_lines }}'