- name: vars
  set_fact:
    password: # str
    palo_provider:
      ip_address: "{{ token_ip.stdout }}"
      api_key: "{{ token_key.stdout }}"

# - name: Show the address object.
#   paloaltonetworks.panos.panos_type_cmd:
#     provider: '{{ palo_provider }}'
#     cmd: 'get'
#     xpath: |
#       /config/shared/local-user-database
#   register: hi

- name: request password hash
  paloaltonetworks.panos.panos_op:
    provider: '{{ palo_provider }}'
    cmd: 'request password-hash password {{password}}'
  register: user_pw

- name: Show phash value
  debug:
    msg: "{{ user_pw.stdout | regex_search('\\$5\\$[a-zA-Z0-9]+\\$[a-zA-Z0-9./]+;') }}"

# - name: Show the address object.
#   paloaltonetworks.panos.panos_type_cmd:
#     provider: '{{ palo_provider }}'
#     cmd: 'set'
#     xpath: |
#       /config/shared/local-user-database/user/entry[@name='testuser']
#     element: |
#       <phash> {{ user_pw.stdout_lines[0].split()[5] }} </phash>


# - name: show user db
#   debug:
#     msg: '{{ hi.stdout }}'