- name: vars
  set_fact:
    palo_provider:
      ip_address: "{{ token_ip.stdout }}"
      api_key: "{{ token_key.stdout }}"

- name: Show the address object.
  paloaltonetworks.panos.panos_op:
    provider: '{{ palo_provider }}'
    cmd: show system info
    # cmd: 'show shared local-user-database'
#   register: hi

# - name: show user db
#   debug:
#     msg: '{{ hi.stdout_lines }}'