- name: vars
  set_fact:
    palo_provider:
      ip_address: "{{ token_ip.stdout }}"
      api_key: "{{ token_key.stdout }}"

- name: get user db.
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ palo_provider }}'
    cmd: 'show'
    xpath: |
      /config/devices/entry[@name='fw1.chg1.inap-lab']
      /vsys/entry[@name='vsys1']
      /address/entry[@name='VM1-PA-Linux']
#   register: hi

# - name: show user db
#   debug:
#     msg: '{{ hi.stdout_lines }}'