- name: vars
  set_fact:
    palo_provider:
      ip_address: "{{ token_ip.stdout }}"
      api_key: "{{ token_key.stdout }}"

- name: get user db.
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ palo_provider }}'
    xpath: |
      /config/devices/entry[@name='fw1.chg1.inap-lab']
      /vsys/entry[@name='vsys1']
      /address
    element: |
      <entry name="sales-block">
        <ip-netmask>192.168.55.0/24</ip-netmask>
        <description>Address CIDR for sales org</description>
      </entry>
#   register: hi

# - name: show user db
#   debug:
#     msg: '{{ hi.stdout_lines }}'