- name: vars
  set_fact:
    password: # str
    palo_provider:
      ip_address: "{{ token_ip.stdout }}"
      api_key: "{{ token_key.stdout }}"

# - name: Show the address object.
#   paloaltonetworks.panos.panos_type_cmd:
#     provider: '{{ palo_provider }}'
#     cmd: 'get'
#     xpath: |
#       /config/shared/local-user-database
#   register: hi

- name: request password hash
  paloaltonetworks.panos.panos_op:
    provider: '{{ palo_provider }}'
    cmd: 'request password-hash password {{password}}'
  register: user_pw

- name: show hash
  debug:
    msg: '{{ user_pw }}'

# - name: Show the address object.
#   paloaltonetworks.panos.panos_type_cmd:
#     provider: '{{ palo_provider }}'
#     cmd: 'get'
#     xpath: |
#       /config/shared/local-user-database


# - name: show user db
#   debug:
#     msg: '{{ hi.stdout }}'