---
- name: gather address groups
  paloaltonetworks.panos.panos_address_group:
    provider: '{{ palo_provider }}'
    gathered_filter: true
    state: gathered
  register: address_group

- name: list results
  debug:
    msg: 
    - 'Name: {{ item.name }}'
    - 'Value: {{ item.static_value }}'
  loop: '{{ address_group.gathered }}'


- name: list results
  debug:
    msg: 'There are no configured address-groups.'
  loop: '{{ address_group.gathered }}'
  when: item | length <=0