- name: vars
  set_fact:
    interface: #str
    zone_name: #str

- name: add interface to zone
  paloaltonetworks.panos.panos_interface:
    provider: '{{ palo_provider }}'
    if_name: '{{interface}}'
    zone_name: '{{zone_name}}'
    enable_dhcp: false
