- name: Get Config Diff 
  paloaltonetworks.panos.panos_op:
    provider: '{{ palo_provider }}'
    cmd_is_xml: true
    cmd: '<show><system><info/></system></show>'
  register: diff

- name: test diff
  debug:
    msg: '{{ diff }}'
