- name: Get Config Diff 
  paloaltonetworks.panos.panos_op:
    provider: '{{ palo_provider }}'
    cmd_is_xml: true
    cmd: '<show><config><running/></config></show>'
  register: running

- name: Get Config Diff 
  paloaltonetworks.panos.panos_op:
    provider: '{{ palo_provider }}'
    cmd_is_xml: true
    cmd: '<show><config><candidate/></config></show>'
  register: candidate

- name: write running to file
  copy:
    content: '{{ running.stdout_xml}}'
    dest: '~/running.txt'
  delegate_to: 172.16.101.183

- name: write running to file
  copy:
    content: '{{ candidate.stdout_xml }}'
    dest: '~/candidate.txt'
  delegate_to: 172.16.101.183

- name: get diff
  shell: diff running.txt candidate.txt
  register: diff
  delegate_to: 172.16.101.183

- name: test diff
  debug:
    msg: '{{diff.stdout_lines}}'

- name: temp cleanup
  shell: rm -f '{{ item }}'
  loop:
    - '~/candidate.txt'
    - '~/running.txt'
  delegate_to: 172.16.101.183
  
