- name: Get Config Diff 
  paloaltonetworks.panos.panos_op:
    provider: '{{ palo_provider }}'
    cmd_is_xml: true
    cmd: '<show><config><running/></config></show>'
  register: diff

- name: test diff
  debug:
    var: diff.stdout_lines
