---

## ANCHOR perform whois lookup
- name: whois lookup
  shell: "{{ whois_command }} '{{ item }}' | grep '{{ org_filter }}'"
  loop: "{{ ips }}"
  register: whois_results
  run_once: true
  delegate_to: 172.16.101.183

  ## ANCHOR Which IP is in our ASN
- name: Determine location from whois data
  debug:
    msg: "{{ item.item }} is {{ 'within' if 'SingleHop' in item.stdout else 'outside of' }} the SingleHop(AS32475) ASN"
  loop: "{{ whois_results.results }}"
  loop_control:
    label: "{{ item.item }}"
  run_once: true