- name: request password hash
  paloaltonetworks.panos.panos_op:
    provider: '{{ palo_provider }}'
    cmd: 'request password-hash password {{password_hash}}'
  register: user_pw

- name: Show the address object.
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ palo_provider }}'
    cmd: 'set'
    xpath: |
      /config/shared/local-user-database/user/entry[@name='{{new_username}}']
    element: |
      <phash>{{ user_pw.stdout_lines[0].split()[5] | regex_replace('[,\"}]', '') }}</phash>