---

## ANCHOR grab mongo creds via kube secrets
- name: grab mongo user
  shell: >
    kubectl -n mongo get secrets mongodb-sec 
    -o go-template='{{ "{{" }} index .data "mongo-username" | base64decode {{ "}}" }}'
  delegate_to: 172.16.101.182 
  run_once: true
  register: mongo_user

- name: grab mongo password
  shell: >
    kubectl -n mongo get secrets mongodb-sec 
    -o go-template='{{ "{{" }} index .data "mongo-password" | base64decode {{ "}}" }}'
  delegate_to: 172.16.101.182
  run_once: true
  register: mongo_pw

- name: grab mongo IP
  shell: kubectl get pod mongo-stateful-0 -o wide -n mongo | awk 'NR==2{print $6}'
  delegate_to: 172.16.101.182
  run_once: true
  register: mongodb_IP



# - name: delete mongo output
#   file:
#     path: /tmp/mongo.js
#     state: absent
#   delegate_to: 172.16.101.182