---

- name: whois lookup
  shell: dig +short "{{ dest | reverse}}".origin.asn.cymru.com TXT | awk 'NR==1{print $1}'
  register: hi

- name: string search
  debug:
    msg: "{{ dest }} is within SingleHop ASN"

- name: test
  debug:
    var: hi