---

- name: craft list
  set_fact:
    ips: ["{{source}}", "{{dest}}"]

- name: declare some vars
  set_fact:
    whois_command: whois
    mtr_command: mtr -rw
    org_filter: OrgName

- name: whois lookup
  shell: "{{ whois_command }} '{{ item }}' | grep {{ org_filter }}"
  loop: "{{ ips }}"
  register: whois_results
  run_once: true
  delegate_to: 172.16.101.182

- name: Determine location from whois data
  debug:
    msg: "{{ item.item }} is {{ 'within' if 'SingleHop' in item.stdout else 'outside of' }} the SingleHop ASN"
  loop: "{{ whois_results.results }}"
  loop_control:
    label: "{{ item.item }}"
  run_once: true

- name: create mtr command
  set_fact:
    mtr_cmd: "{{ mtr_command }} '{{ item }}'"
  loop: "{{ ips }}"

- name: Ensure MTR is installed
  package:
    name: mtr
    state: present
  when: ansible_facts['pkg_mgr'] in ['apt', 'yum', 'dnf']

- name: run mtr for each IP
  shell: "{{ mtr_command }} '{{ item }}'"
  loop: "{{ ips }}"
  register: mtrout
  loop_control:
    label: "{{ item }}"

- name: Show MTR results for each IP
  debug:
    msg: "MTR results for {{ item.item }}: {{ item.stdout_lines }}"
  loop: "{{ mtrout.results }}"
  loop_control:
    label: "{{ item.item }}"