---

- name: craft list
  set_fact:
    ips: ["{{source}}", "{{dest}}"]

- name: whois lookup
  shell: whois "{{ item }}" | grep OrgName
  loop: "{{ ips }}"
  register: whois_results
  run_once: true
  delegate_to: 172.16.101.182

- name: Determine location from whois data
  debug:
    msg: "{{ item.item }} is {{ 'within' if 'SingleHop' in item.stdout else 'outside of' }} the SingleHop ASN"
  loop: "{{ whois_results.results }}"
  loop_control:
    label: "{{ item.item }}"
  run_once: true

- name: check for mtr package 
  apt:
    name: mtr
    state: present
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: run mtr 
  shell: mtr -rw "{{ source }}"
  register: mtrout

- name: mtr results 
  debug:
    var: mtrout.stdout_lines