---

# - name: whois lookup
#   shell: dig +short "{{ dest | reverse}}".origin.asn.cymru.com TXT | awk 'NR==1{print $1}'
#   register: hi

- name: whois lookup
  shell: whois "{{ dest }}"
  register: whois
  delegate_to: 172.16.101.182

# - name: string search
#   debug:
#     msg: "{{ dest }} is within SingleHop ASN"
#   when: "{{ whois.stdout is search('SingleHop') }}"

- name: test
  debug:
    var: whois.stdout_lines