---

- name: Perform Patch Dryrun
  vmware_cluster_info module:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: CHG1
  delegate_to: localhost
  register: cluster_info

- name: debug
  debug:
    var: cluster_info.stdout

