---

  - name: Perform Patch Dryrun
    shell: 'esxcli software vib update -d /vmfs/volumes/{{datastore}}/VMware-Tools-12.3.0-core-offline-depot-ESXi-all-22234872.zip --dry-run'
    register: dryoutput

  - name: Print dry run results
    debug:
      var: dryoutput.stdout_lines

  - name: Sending an e-mail using Gmail SMTP servers
    community.general.mail:
      host: smtp.gmail.com
      port: 587
      username: {{ user }}
      password: {{ pass }}
      to: {{ recipient }}
      subject: Ansible-report
      body: dryoutput.stdout_lines
    delegate_to: localhost
