- name: Add IKE gateway config to the firewall
  paloaltonetworks.panos.panos_ike_gateway:
    provider: '{{ palo_provider }}'
    name: '{{ gateway }}'
    state: gathered
  register: ike_mode

- name: hi
  debug:
    var: ike_mode.gathered