- name: add a nat rule
  paloaltonetworks.panos.panos_nat_rule2:
    provider: '{{ palo_provider }}'
    name: '{{ NAT_rule_name }}'
    description: 'Made by AWX'
    nat_type: 'ipv4'
    from_zones: ['{{ NAT_source_zone }}']
    to_zones: ['{{ NAT_dest_zone }}']
    to_interface: 'any'
    service: 'any'
    source_addresses: ['{{ NAT_source_object_name }}']
    destination_addresses: ['any']
    source_translation_type: 'static-ip'
    source_translation_static_translated_address: '{{ NAT_translated_object_name }}'
    source_translation_static_bi_directional: true