---

## ANCHOR convert the JSON to HTML
- name: run our python script
  shell: python3 /tmp/convert.py
  register: html
  run_once: true
  delegate_to: 172.16.101.182

  ## ANCHOR insert our JSON output into MongoDB
- name: send output to mongo
  community.mongodb.mongodb_shell:
    login_host: "{{ mongodb_IP.stdout }}"
    login_user: "{{ mongo_user.stdout }}"
    login_password: "{{ mongo_pw.stdout }}"
    file: "/tmp/mongo.js"
  delegate_to: 172.16.101.182
  run_once: true