- name: Create User & set password hash.
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ palo_provider }}'
    cmd: 'delete'
    xpath: |
      /config/devices/entry[@name='localhost.localdomain']
      /vsys/entry[@name='vsys1']
      /rulebase/security/rules/entry[@name='Blacklisted IPs']
    element: |
      <source>{{ blocked_IP }}-Blacklisted</source>