- name: Gather ACL Facts
  paloaltonetworks.panos.panos_security_rule:
    provider: '{{ palo_provider }}'
    state: gathered
    gather_filter: true
  register: acl

- name: print
  debug:
    msg: '{{acl.gathered}}'