- name: Gather ACL Facts
  paloaltonetworks.panos.panos_security_rule:
    provider: '{{ palo_provider }}'
    rule_name: 'Blacklisted IPs'
    state: gathered
  register: acl

- name: print
  debug:
    msg: '{{ acl.gathered.source_ip }}'

