- name: Disable Local User
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ palo_provider }}'
    cmd: 'set'
    xpath: |
      /config/shared/local-user-database/user/entry[@name='{{VPN_user_disabled_username}}']
    element: |
      <disabled>yes</disabled>