---

- name: Create object 'Test-One'
  paloaltonetworks.panos.panos_address_object:
    provider: '{{ palo_provider }}'
    name: '{{ item }}'
    value: '{{ item }}'
    description: 'made by ansible'
  loop:
    - '1.1.1.1'
    - '2.2.2.2'