---

- name: Get running nat-policy
  paloaltonetworks.panos.panos_op:
    provider: '{{ palo_provider }}'
    cmd: 'show running nat-policy'
  register: nat_policy_raw

- name: Convert NAT policy string to structured data
  set_fact:
    nat_policy_lines: "{{ nat_policy_raw.stdout_lines }}"

- name: Display each NAT policy
  debug:
    var: nat_policy_lines | from_json