---

- name: get id of awx
  shell: cat /var/lib/awx/hi
  register: hi

- name: debug
  debug:
    var: hi.stdout


# - name: Get facts
#   paloaltonetworks.panos.panos_facts:
#     provider: '{{ palo_provider }}'
#   register: test

# - name: debug
#   debug:
#     var: test.stdout_lines