---

- name: pip
  become: true
  shell: pip install pan-python

# - name: Get facts
#   paloaltonetworks.panos.panos_facts:
#     provider: '{{ palo_provider }}'
#   register: test

# - name: debug
#   debug:
#     var: test.stdout_lines