---

- name: Get facts
  paloaltonetworks.panos.panos_op:
    provider: '{{ palo_provider }}'
    cmd: 'show interface ethernet1/1'
  register: test
  
- name: debug
  debug:
    var: test.stdout_lines