---

# - name: Change user password
#   user:
#     name: root
#     update_password: always
#     password: "toor"

- name: djhsuo
  shell: hostname
  register: out

- name: debug
  debug:
    var: out.stdout


# - name: Create object 'Test-One'
#   paloaltonetworks.panos.panos_address_object:
#     provider: '{{ palo_provider }}'
#     name: 'Test-One'
#     value: '172.16.203.15/32'
#     description: 'made by ansible'

# - name: Create object 'Test-One-NAT'
#   paloaltonetworks.panos.panos_address_object:
#     provider: '{{ palo_provider }}'
#     name: 'Test-One-NAT'
#     value: '198.20.64.242/32'
#     description: 'made by ansible'
