---

- name: Get running nat-policy
  paloaltonetworks.panos.panos_op:
    provider: '{{ palo_provider }}'
    cmd: 'show running nat-policy'
  register: nat_policy_raw

- name: Parse NAT Policy stdout to JSON
  set_fact:
    nat_policy_json: "{{ nat_policy_raw.stdout | from_json }}"

- name: Extract NAT policy details
  set_fact:
    nat_details: "{{ nat_policy_json.response.result.member }}"

- name: Display NAT details in structured format
  debug:
    msg: |
      NAT Type: {{ item.nat-type }}
      From Zone: {{ item.from }}
      Source: {{ item.source }}
      To Zone: {{ item.to }}
      To Interface: {{ item.to-interface }}
      Destination: {{ item.destination }}
      Service: {{ item.service }}
      Translate To: {{ item.translate-to }}
      Terminal: {{ item.terminal }}
  loop: "{{ nat_details }}"
