- name: Create object group
  paloaltonetworks.panos.panos_address_group:
    provider: '{{ palo_provider }}'
    name: '{{address_group_name}}'
    static_value: "{{address_object_name_to_add}}"
    state: present