- name: Gather ACL Facts
  paloaltonetworks.panos.panos_security_rule:
    provider: '{{ palo_provider }}'
    rule_name: 'Blacklisted IPs'
    state: gathered
  register: acl

- name: Form output
  set_fact:
    acls: "{{ acl.gathered.source_ip | rejectattr('search', 'match', '-Blacklisted') }}"

- name: print blocked IP's
  debug:
    msg: '{{ acls }}'