---
- name: gather every NAT policy
  paloaltonetworks.panos.panos_address_object:
    provider: '{{ palo_provider }}'
    gathered_filter: true
    state: gathered
  register: address_obj_result

- name: list every NAT policy
  debug:
    msg: 
      - '{{ address_obj_result.gathered }}'