---
- name: gather every NAT policy
  paloaltonetworks.panos.panos_address_object:
    provider: '{{ palo_provider }}'
    gathered_filter: true
    state: gathered
  register: address_obj_result

- name: list every NAT policy
  debug:
    msg: 
      - 'Name: {{ item.name }}'
      - 'Address-type: {{ item.address_type }}'
      - 'Value: {{ item.value }}'
  loop: '{{ address_obj_result.gathered }}'
  register: desired_out


- name: write data locally
  copy:
    content: '{{ desired_out }}'
    dest: "~/values.txt"
  loop: '{{ address_obj_result.gathered }}'
  delegate_to: 172.16.101.183