---

## ANCHOR give our HTML a css stylesheet
- name: css style
  blockinfile:
    path: /root/nginx-content/index.html
    insertbefore: "<table b"
    block: |
      <head>
        <link rel="stylesheet" type="text/css" href="style.css">
      </head>
  delegate_to: 172.16.101.182

## ANCHOR get rid of markers in html file
- name: cleanup markers
  lineinfile: 
    path: "/root/nginx-content/index.html"
    line: "{{ item }}"
    state: absent
  loop:
    - "# BEGIN ANSIBLE MANAGED BLOCK"
    - "# END ANSIBLE MANAGED BLOCK"
  delegate_to: 172.16.101.182
  run_once: true

- name: delete mongo output
  file:
    path: /tmp/mongo.js
    state: absent
  delegate_to: 172.16.101.182

- name: delete python script
  file:
    path: /tmp/convert.py
    state: absent
  delegate_to: 172.16.101.182

- name: delete json output
  file:
    path: /tmp/master.json
    state: absent
  delegate_to: 172.16.101.182