---
- name: gather every NAT policy
  paloaltonetworks.panos.panos_nat_rule2:
    provider: '{{ palo_provider }}'
    gathered_filter: true
    state: gathered
  register: nat_result

- name: list every NAT policy
  debug:
    msg: 
    - '{{ item.name }}'
    - '{{ item.from_zones }}'
    - '{{ item.source_addresses }}'
    - '{{ item.to_zones }}'
    - '{{ item.destination_addresses }}'
  loop: '{{ nat_result.gathered }}'