---

- name: Create PA APi Key
  ansible.builtin.uri:
    url: "https://{{ IP_address }}/api/?type=keygen"
    method: POST
    body_format: form-urlencoded
    body:
    - [ user, '{{ username }}' ]
    - [ password, '{{ pass }}' ]
    validate_certs: false
    return_content: true
  no_log: false
  register: login

- name: Parse key from XML response
  set_fact:
    parsed_response: "{{ login.content | ansible.utils.from_xml }}"
  no_log: false
  
- name: Extract key
  set_fact:
    api_key: "{{ parsed_response['response']['result']['key'] }}"
  no_log: false
  
- name: create provider
  set_fact:
    palo_provider:
      ip_address: "{{ IP_address }}"
      api_key: "{{ api_key }}"
  no_log: false