---

- name: login to vault
  community.hashi_vault.vault_login:
    url: http://172.16.101.183:8200
    auth_method: token
    token_file: /home/Administrator/token
  register: login_data
  delegate_to: 172.16.101.183

- name: create dynamic selector
  set_fact:
    dropdown_opt: #str == client

- name: gather secret from vault
  set_fact:
    response: "{{ lookup('community.hashi_vault.vault_kv2_get', dropdown_opt, url='http://172.16.101.183:8200', token=login_data.login.auth.client_token) }}"

- name: vars
  set_fact:
    TrainingVCSA:
      vc_name: "{{response.secret.vc_name}}"
      user: "{{response.secret.user}}"
      pass: "{{response.secret.pass}}"

- name: run rvtools
  win_shell: C:\Scripts\rvtoolsps1.ps1 -VCServer "{{TrainingVCSA.vc_name}}" -User "{{TrainingVCSA.user}}" -password '{{TrainingVCSA.pass}}'

- name: Display the results
  ansible.builtin.debug:
    msg:
      - "{{ TrainingVCSA.vc_name }}"
      - "{{ TrainingVCSA.user }}"
      - "{{ TrainingVCSA.pass }}"