---
- name: vars
  set_fact:
    dropdown_opt: #str == client
    TrainingVCSA:
      vc_name: 
      user: 
      pass: 

# - name: run rvtools
#   win_shell: rvtools -S '{{ dropdown_opt[vc_name] -u dropdown_opt[user] -p dropdown_opt[pass] }}' -c ExportAll2csv -f /path/to/whatever.csv


- name: login to vault
  community.hashi_vault.vault_login:
    auth_method: token
  register: login_data



- name: Display the results
  ansible.builtin.debug:
    msg:
      - "Secret: {{ login_data }}"