---

- name: login to vault
  community.hashi_vault.vault_login:
    url: http://172.16.101.183:8200
    auth_method: token
    token_file: /root/token
  register: login_data

- name: gather secret from vault
  set_fact:
    response: "{{ lookup('community.hashi_vault.vault_kv2_get', 'creds', url='http://172.16.101.183:8200', token=login_data.login.auth.client_token) }}"

- name: vars
  set_fact:
    dropdown_opt: #str == client
    TrainingVCSA:
      vc_name: 
      user: "{{response.secret.user}}"
      pass: "{{response.secret.pass}}"

# - name: run rvtools
#   win_shell: rvtools -S '{{ dropdown_opt[vc_name] -u dropdown_opt[user] -p dropdown_opt[pass] }}' -c ExportAll2csv -f /path/to/whatever.csv






- name: Display the results
  ansible.builtin.debug:
    msg:
      - "{{ TrainingVCSA.user }}"
      - "{{ TrainingVCSA.pass }}"