---

- name: create client selector
  set_fact:
    dropdown_opt: #str == client

- name: Gather secret from Vault
  community.hashi_vault.vault_kv2_get:
    url: '{{ ansible_hashi_vault_addr }}'
    path: '{{ dropdown_opt }}'
    auth_method: '{{ ansible_hashi_vault_auth_method }}'
    role_id: '{{ ansible_hashi_vault_role_id }}'
    secret_id: '{{ ansible_hashi_vault_secret_id }}'
  register: response
  delegate_to: localhost

- name: Store vault results
  set_stats:
    data:
      Client:
        vc_name: "{{response.secret.vc_name}}"
        user: "{{response.secret.user}}"
        pass: "{{response.secret.pass}}"
  no_log: true

- name: run rvtools
  no_log: true
  win_shell: C:\Scripts\rvtoolsps1.ps1 -VCServer "{{Client.vc_name}}" -User "{{Client.user}}" -password '{{Client.pass}}'