---
- name: create dynamic selector
  set_fact:
    dropdown_opt: #str == client

- name: Gather secret from Vault
  community.hashi_vault.vault_kv2_get:
    url: http://172.16.101.183:8200
    path: '{{ dropdown_opt }}'
    auth_method: token
    token_file: /root/.token
  register: response

- name: Store vault results
  set_fact:
    Client:
      vc_name: "{{response.secret.vc_name}}"
      user: "{{response.secret.user}}"
      pass: "{{response.secret.pass}}"
