---

- name: Date of Last Reboot
  shell: 'last reboot | head'
  register: reboot

- name: Date of Last Update
  shell: "rpm -qa -last | awk '{print $2 , $4 , $5}' | sort -k3,3nr -k2,2M -k1,1 | uniq | head"
  register: update

- name: grab hostname and IP's
  shell: hostname; ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p';
  register: ip

- name: Check Fixes
  shell: 'yum updateinfo'
  register: Sec_Impact

- name: Print Hostname & IP(s)
  debug:
    var: ip.stdout_lines

- name: Print Last Update
  debug:
    var: update.stdout_lines

- name: Print Last Reboot
  debug:
    var: reboot.stdout_lines

- name: Print Bug/Security Fixes
  debug:
    var: Sec_Impact.stdout_lines 

- name: check the CentOS version
  debug:
    msg: "Found CentOS 7 or bigger"
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7" 
