- name: vars
  set_fact:
    password_hash: # str
    palo_provider:
      ip_address: "{{ token_ip.stdout }}"
      api_key: "{{ token_key.stdout }}"

- name: Show the address object.
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ palo_provider }}'
    cmd: 'get'
    xpath: |
      /config/shared/local-user-database
  register: hi

- name: show user db
  debug:
    msg: '{{ hi.stdout }}'