- name: Show the address object.
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ palo_provider }}'
    cmd: 'get'
    xpath: |
      /config/shared/local-user-database
  register: hi

- name: show user db
  debug:
    msg: '{{ hi.stdout }}'