- name: drop from outside
  paloaltonetworks.panos.panos_security_rule:
    provider: '{{ palo_provider }}'
    gathered_filter: true
    state: gathered
  register: acl

- name: print acl
  debug:
    msg: 
    - '{{ item.rule_name }}'
    - '{{ item.application }}'
    - '{{ item.action }}'
    - '{{ item.source_zone }}'
    - '{{ item.source_ip }}'
    - '{{ item.destination_zone }}'
    - '{{ item.destination_ip }}'
  loop: '{{ acl.gathered }}'