- name: drop from outside
  paloaltonetworks.panos.panos_security_rule:
    provider: '{{ palo_provider }}'
    gathered_filter: true
    state: gathered
  register: acl

- name: print acl
  debug:
    msg: 
    - 'Rule: {{ item.rule_name }}'
    - 'Application: {{ item.application }}'
    - 'Action: {{ item.action }}'
    - 'Source Zone: {{ item.source_zone }}'
    - 'Source IP: {{ item.source_ip }}'
    - 'Destination Zone: {{ item.destination_zone }}'
    - 'Destination IP: {{ item.destination_ip }}'
  loop: '{{ acl.gathered }}'