- name: Create address object
  paloaltonetworks.panos.panos_address_object:
    provider: '{{ palo_provider }}'
    name: '{{ object_name }}'
    value: '{{ source_ip }}'
    description: 'made by ansible'

