---

- name: Create Remote Peer
  paloaltonetworks.panos.panos_address_object:
    provider: '{{ palo_provider }}'
    name: 'test vpn'
    value: '1.1.1.1'
    description: 'made by ansible'

- name: create tunnel
  paloaltonetworks.panos.panos_tunnel:
    provider: '{{ palo_provider }}'
    if_name: "tunnel.1"
    ip: 
    zone_name: 'dmz'
    management_profile: 'allow-ping'

- name: Add IKE gateway config to the firewall
  paloaltonetworks.panos.panos_ike_gateway:
    provider: '{{ palo_provider }}'
    name: 'IKEGW-Ansible'
    version: 'ikev2'
    ikev1_exchange_mode: 'main'
    interface: 'ethernet1/1'
    enable_passive_mode: false
    enable_liveness_check: true
    liveness_check_interval: '5'
    peer_ip_value: '1.2.3.5'
    pre_shared_key: 'CHANGEME'
    ikev2_crypto_profile: 'default'

- name: Add IPSec tunnel to IKE gateway profile
  paloaltonetworks.panos.panos_ipsec_tunnel:
    provider: '{{ palo_provider }}'
    name: 'IPSecTunnel-Ansible'
    tunnel_interface: 'tunnel.1'
    ak_ike_gateway: 'IKEGW-Ansible'
    ak_ipsec_crypto_profile: 'default'

- name: Create route 'Test-One'
  paloaltonetworks.panos.panos_static_route:
    provider: '{{ provider }}'
    name: 'Test-One'
    destination: 'IPSecTunnel-Ansible'
    nexthop_type: 'none'