- name: drop from outside
  paloaltonetworks.panos.panos_security_rule:
    provider: '{{ palo_provider }}'
    rule_name: 'Client Managed Block List'
    description: 'Made by AWX'
    source_zone: ['OUTSIDE']
    source_ip: ['Client_managed_Block_Group']
    destination_zone: ['any']
    destination_ip: ['any']
    application: ['any']
    action: 'drop'
    location: top
    log_end: true
