- name: Gather IKE Gateway Facts
  paloaltonetworks.panos.panos_ike_gateway:
    provider: '{{ palo_provider }}'
    name: 'test'
    state: gathered
  register: ike_mode

- name: Print IKE Gateway Facts
  debug:
    msg:
      - 'Name: {{ item.gathered.name }}'
      - 'Version: {{ item.gathered.version }}'
      - 'Interface: {{ item.gathered.interface }}'
      - 'Peer IP Value: {{ item.gathered.peer_ip_value }}'
      - 'Mode: {{ item.gathered.ikev1_exchange_mode }}'
      - 'Crypto Profile: {{ item.gathered.ikev2_crypto_profile }}'
  loop: '{{ ike_mode.gathered | dict2items }}'

# - name: Add IKE gateway config to the firewall
#   paloaltonetworks.panos.panos_ike_gateway:
#     provider: '{{ palo_provider }}'
#     name: '{{ gateway }}'
#     state: gathered
#   register: ike_mode

# - name: Add IKE gateway config to the firewall
#   paloaltonetworks.panos.panos_ike_gateway:
#     provider: '{{ palo_provider }}'
#     name: '{{ gateway }}'
#     peer_ip_value: "{{ ike_mode.gathered.peer_ip_value }}"
#     ikev1_exchange_mode: '{{ mode }}'
#     state: merged
