- name: Add IKE gateway config to the firewall
  paloaltonetworks.panos.panos_ike_gateway:
    provider: '{{ palo_provider }}'
    name: '{{ gateway }}'
    state: gathered
  register: ike_mode

- name: Add IKE gateway config to the firewall
  paloaltonetworks.panos.panos_ike_gateway:
    provider: '{{ palo_provider }}'
    name: '{{ gateway }}'
    peer_ip_value: "{{ ike_mode.gathered.peer_ip_value }}"
    ikev1_exchange_mode: '{{ mode }}'
    state: merged
