- name: Add IKE gateway config to the firewall
  paloaltonetworks.panos.panos_ike_gateway:
    provider: '{{ palo_provider }}'
    name: 'test'
    state: 'gathered'
  register: ike_mode

- name: New List
  set_fact:
    value: "{{ ike_mode.gathered }}"

# - name: Add IKE gateway config to the firewall
#   paloaltonetworks.panos.panos_ike_gateway:
#     provider: '{{ palo_provider }}'
#     name: 'test'
#     ikev1_exchange_mode: 'main'
#     state: merged
