- name: Create object group 'block_from_outside'
  paloaltonetworks.panos.panos_address_group:
    provider: '{{ palo_provider }}'
    name: 'Client_managed_Block_Group'
    gathered_filter: true
    state: gathered
    register: out

- name: djsaio
  debug:
    msg: '{{ out.gathered}}'
