# - name: Create object group 'block_from_outside'
#   paloaltonetworks.panos.panos_address_group:
#     provider: '{{ palo_provider }}'
#     name: 'Client_managed_Block_Group'
#     static_value: ['{{object_name}}']
#     state: deleted


- name: Delete specific object from address-group
  paloaltonetworks.panos.panos_type_cmd:
    provider: '{{ palo_provider }}'
    cmd: 'delete'
    xpath: >-
      /config/devices/entry[@name='localhost.localdomain']
      /vsys/entry[@name='vsys1']
      /address-group/entry[@name='Client_managed_Block_Group']/static/member[text()='{{ object_name }}']
